version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5454:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: {}
